apiVersion: apps/v1
kind: Deployment
metadata:
  name: dedup-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dedup-app
  template:
    metadata:
      labels:
        app: dedup-app
    spec:
      containers:
        - name: dedup-app
          image: muhammedsaheen/dedup:latest
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__MySql
              value: "Server=mysql;Database=deduplication;User Id=root;Password=root;"
            - name: RabbitMQ__Host
              value: "rabbitmq"
            - name: RabbitMQ__Queue
              value: "event_queue"
---
apiVersion: v1
kind: Service
metadata:
  name: dedup-app
spec:
  type: NodePort
  selector:
    app: dedup-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000

